### ISSUE TITLE
Rename core function

### ISSUE THREAD

**Issue by ChHaeni** [sashahafner/ALFAM2#35]
Can we rename `ALFAM2mod` to `alfam2_mod` or even `alfam2`?

**Comment by sashahafner** [comment]
Just to make typing easier? That's a big change, but I'm not against it. We could keep `ALFAM2mod()` as an alias. Originally, the package was going to have measurements and the model, so I/we probably added "mod" to distinguish. 

I like `alfam2()`.

**Comment by sashahafner** [comment]
Changed. `ALFAM2mod()` is an alias. 
e7cd3d47c9a3abf8f58b1cbff1e0afc45dd80848

**Comment by sashahafner** [comment]
Changed par vector names in 51f0062f1fd2786de12787557d623f086e59e321
Capital (uppercase) versions are still aliases, but I did not save uppercase and lowercase in separate Rda files because `R CMD  check --as-cran` throws an error, because not all operating systems can handle the distinction. So 2 Rda files have 4 objects. Seems to work, and no complaints from the as-cran check.
